apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.environment }}
    owner: {{ .Values.app.owner }}
  annotations:
    # enable owasp rules protection
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    
    # basic DoS protection
    nginx.ingress.kubernetes.io/limit-rps: "10"
    
    # enable support for url-rewrite with regex support
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}
            port:
              number: {{ .Values.ingress.port }}
  ingressClassName: nginx